name = "notifytg"
main = "src/index.js"
compatibility_date = "2023-05-12"
[ vars ]
TOKEN = "tokenhere"
send_email = [
    {type = "send_email", name = "SEB"},
]
CFURL = "https://polished-fog-c5e2.yuanzhisheng.workers.dev/"

[[ d1_databases ]]
binding = "DB"
database_name = "emaildb"
database_id = "idhere"
